/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hr.algebra;

import hr.algebra.model.Users;
import hr.algebra.utilities.MessageUtils;
import hr.algebra.view.EditArticlesPanel;
import hr.algebra.view.EditUsers;
import hr.algebra.view.UploadArticlesPanel;
import java.util.Optional;
import java.util.prefs.Preferences;
import javax.swing.JOptionPane;

/**
 *
 * @author daniel.bele
 */
public class ArticleManager extends javax.swing.JFrame {

    private Users loggedInUser;
    private static final String UPLOAD_ARTICLES = "Upload articles";
    private static final String EDIT_ARTICLES = "Edit articles";

    /**
     * Creates new form ArticleManager
     */
    public ArticleManager() {
        initComponents();
        configurePanels();

    }

    public ArticleManager(Users user) {
        this.loggedInUser = user;
        initComponents();
        configurePanels();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tpContent = new javax.swing.JTabbedPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        miExit = new javax.swing.JMenuItem();
        miLogOut = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        miEditRoles = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("File");

        miExit.setText("Exit");
        miExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miExitActionPerformed(evt);
            }
        });
        jMenu1.add(miExit);

        miLogOut.setText("Log-out");
        miLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miLogOutActionPerformed(evt);
            }
        });
        jMenu1.add(miLogOut);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");

        miEditRoles.setText("Roles");
        miEditRoles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miEditRolesActionPerformed(evt);
            }
        });
        jMenu2.add(miEditRoles);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tpContent, javax.swing.GroupLayout.DEFAULT_SIZE, 1280, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tpContent, javax.swing.GroupLayout.DEFAULT_SIZE, 797, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void miExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miExitActionPerformed

        dispose();
    }//GEN-LAST:event_miExitActionPerformed

    private void miLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miLogOutActionPerformed
        
        

        if (MessageUtils.showConfirmDialog("LogOut", "Are you sure?")) {
            // Zatvori trenutni prozor
            this.dispose();

            // Otvori LoginRegisterScreen
            java.awt.EventQueue.invokeLater(() -> {
                new LoginRegisterScreen().setVisible(true);
            });
        }

    }//GEN-LAST:event_miLogOutActionPerformed

    private void miEditRolesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miEditRolesActionPerformed
       java.awt.EventQueue.invokeLater(() -> {
        new EditUsers().setVisible(true);
    });
    }//GEN-LAST:event_miEditRolesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ArticleManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ArticleManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ArticleManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ArticleManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ArticleManager().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem miEditRoles;
    private javax.swing.JMenuItem miExit;
    private javax.swing.JMenuItem miLogOut;
    private javax.swing.JTabbedPane tpContent;
    // End of variables declaration//GEN-END:variables

    private void configurePanels() {

        tpContent.add(UPLOAD_ARTICLES, new UploadArticlesPanel());

        if (loggedInUser != null && loggedInUser.isAdmin()) {
            tpContent.add(EDIT_ARTICLES, new EditArticlesPanel());
        } else {
            jMenu2.setVisible(false); // sakrije "Edit -> Roles"
        }

    }
}
