/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hr.algebra.view;

import hr.algebra.dal.Repository;
import hr.algebra.dal.RepositoryFactory;
import hr.algebra.model.Users;
import hr.algebra.utilities.MessageUtils;
import java.util.List;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Bruno
 */
public class EditUsers extends javax.swing.JFrame {

    /**
     * Creates new form EditUsers
     */
    private Repository repository;
    private List<Users> users;
    private JTable tblUsers;
    private JButton btnSave;

    private int selectedUserId = -1;         // trenutačno selektirani

    public EditUsers() {
        initComponents();
        init();
        loadTable();
        initListeners();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbUsers = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tpLastName = new javax.swing.JTextPane();
        lbLastName = new javax.swing.JLabel();
        lbFirstName = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tpFirstName = new javax.swing.JTextPane();
        btnSaveChange = new javax.swing.JButton();
        cbIsAdmin = new javax.swing.JCheckBox();
        btnReturn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1280, 960));

        tbUsers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "First Name", "Last Name", "Username", "Password", "E-mail", "Admin"
            }
        ));
        tbUsers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbUsersMouseClicked(evt);
            }
        });
        tbUsers.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tbUsersKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tbUsers);

        jScrollPane2.setViewportView(tpLastName);

        lbLastName.setText("Last name:");

        lbFirstName.setText("First name:");

        jScrollPane3.setViewportView(tpFirstName);

        btnSaveChange.setText("Save");
        btnSaveChange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveChangeActionPerformed(evt);
            }
        });

        cbIsAdmin.setText("Admin");

        btnReturn.setText("Return");
        btnReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReturnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1268, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lbLastName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbFirstName, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE))
                        .addGap(66, 66, 66)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbIsAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSaveChange, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnReturn, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 372, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                    .addComponent(lbFirstName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbLastName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(cbIsAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSaveChange, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(112, 112, 112)
                .addComponent(btnReturn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tbUsersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbUsersMouseClicked

    }//GEN-LAST:event_tbUsersMouseClicked

    private void tbUsersKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbUsersKeyReleased

    }//GEN-LAST:event_tbUsersKeyReleased

    private void btnSaveChangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveChangeActionPerformed
        if (selectedUserId == -1) {
            MessageUtils.showInformationMessage("Info", "Please select a user first!");
            return;
        }

        boolean showConfirmDialog = MessageUtils.showConfirmDialog("T'fck are you doing", "Are you really really sure");

        if (showConfirmDialog == true) {
            try {
                boolean newAdmin = cbIsAdmin.isSelected();
                repository.updateUserRole(selectedUserId, newAdmin);

                MessageUtils.showInformationMessage("Success", "Role updated!");
                loadTable();                 // osvježi tablicu
                // po želji: clearForm();
            } catch (Exception ex) {
                ex.printStackTrace();
                MessageUtils.showErrorMessage("Error", "Failed to update role");
            }
        }
    }//GEN-LAST:event_btnSaveChangeActionPerformed

    private void btnReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReturnActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnReturnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditUsers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditUsers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditUsers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditUsers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditUsers().setVisible(true);
            }
        });
    }

    private void init() {
        try {
            repository = RepositoryFactory.getRepository();
            users = repository.selectUsers(); // metoda koja vraća sve korisnike iz baze

            String[] columns = {"UserID", "First Name", "Last Name", "Username", "Email", "isAdmin"};
            Object[][] data = new Object[users.size()][6];

            for (int i = 0; i < users.size(); i++) {
                Users u = users.get(i);
                data[i][0] = u.getId();
                data[i][1] = u.getFirstName();
                data[i][2] = u.getLastName();
                data[i][3] = u.getUserName();
                data[i][4] = u.getEmail();
                data[i][5] = u.isAdmin();
            }

            

            JScrollPane scrollPane = new JScrollPane(tblUsers);
            getContentPane().add(scrollPane, java.awt.BorderLayout.CENTER);

            
            setTitle("Edit Roles");
            setSize(950, 650);
            setLocationRelativeTo(null);
        } catch (Exception ex) {
            ex.printStackTrace();
            MessageUtils.showErrorMessage("Error", "Cannot load users");
        }
    }

    

    private void initListeners() {
        tbUsers.getSelectionModel().addListSelectionListener(e -> {
            if (!e.getValueIsAdjusting() && tbUsers.getSelectedRow() >= 0) {
                int row = tbUsers.convertRowIndexToModel(tbUsers.getSelectedRow());
                Users u = users.get(row);
                selectedUserId = u.getId();
                tpFirstName.setText(u.getFirstName());
                tpLastName.setText(u.getLastName());
                cbIsAdmin.setSelected(u.isAdmin());
            }
        });
    }

    private void loadTable() {
        try {
            users = repository.selectUsers();
            String[] cols = {"ID", "First Name", "Last Name", "Username", "E-mail", "Admin"};
            DefaultTableModel tm = new DefaultTableModel(cols, 0) {
                @Override
                public boolean isCellEditable(int r, int c) {
                    return false;
                }

                @Override
                public Class<?> getColumnClass(int c) {
                    return c == 5 ? Boolean.class : String.class;
                }
            };
            for (Users u : users) {
                tm.addRow(new Object[]{
                    u.getId(),
                    u.getFirstName(),
                    u.getLastName(),
                    u.getUserName(),
                    u.getEmail(),
                    u.isAdmin()
                });
            }
            tbUsers.setModel(tm);
            tbUsers.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        } catch (Exception ex) {
            ex.printStackTrace();
            MessageUtils.showErrorMessage("Error", "Cannot load users!");
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReturn;
    private javax.swing.JButton btnSaveChange;
    private javax.swing.JCheckBox cbIsAdmin;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lbFirstName;
    private javax.swing.JLabel lbLastName;
    private javax.swing.JTable tbUsers;
    private javax.swing.JTextPane tpFirstName;
    private javax.swing.JTextPane tpLastName;
    // End of variables declaration//GEN-END:variables

}
